### ISSUE TITLE
Issues that need to be fixed.

### ISSUE THREAD

**Issue by somepeopledontknow** [mavropalias/Hero35#3]
**Thanks so much for making this open source! Love the design and everything about it :) I spotted a few issues.** 

1) If you login and go to https://hero35.com/saved-talks it returns an internal server error 500 message.
2) If you like an event/talk .. it doesn't let you unlike it. Clicking the like button again doesn't do anything.
3) I noticed in some of your functions code on the server, you're missing a few `return` statements in various spots. (An example of what i'm talking about is this) https://github.com/mavropalias/Hero35/blob/8122c134ca9a1cbc87c4bc4643fa894cdc806730/src/functions/index.ts#L212 There's various other spots that also have missing `return` statements in front of the `response.send` functions :)
**Edit**: Fixed all the missing return statements with this PR: https://github.com/mavropalias/Hero35/pull/4

4) I also don't see any functions to add/delete talks from the database. **How are new talks added to the database?**
5) I see there's a `/country/[countryid]` route included in the project.. however don't see any pages that link to that page. Is this a page that was just never used or maybe is upcoming?

I will keep updating this thread if you'd like to keep it open, and I can help spot errors as you add new updates, etc! @mavropalias

**Comment by somepeopledontknow** [comment]
Stumbled upon a few more things that i'm a little concerned about with the cloud functions..
1) For your `likeTalk` and `dislikeTalk` functions; you're storing the `dislikedUids` inside an array on the talk document. 
https://github.com/mavropalias/Hero35/blob/8122c134ca9a1cbc87c4bc4643fa894cdc806730/src/functions/index.ts#L656
From all the documentation on Firebase i've read, they have said that storing anything that has the ability to grow to an undetermined size should not be stored inside arrays, but rather inside a collection inside the document (using collection groups). Wouldn't it be better to store `Likes` and `Dislikes` inside a collection within the talk document they belong to? That way you could do something like `query(talkDocument)->query(likesSubCollection)->query(where(userId==x))` and same for dislikes.

**Note**: It look's like you're doing the same thing with a user saving talks. I think the best approach would be to similarly add the saves to a collection under the talk document it belongs to?

Curious about your thoughts on what I mentioned, and please let me know if you disagree! I'm new to Firestore, so I could be completely wrong :)

**Comment by mavropalias** [comment]
> **Thanks so much for making this open source! Love the design and everything about it :) I spotted a few issues.**

Hi, and thank you so much for the kind words and taking the time to provide feedback. I appreciate it!

> 1. If you login and go to https://hero35.com/saved-talks it returns an internal server error 500 message.
> 2. If you like an event/talk .. it doesn't let you unlike it. Clicking the like button again doesn't do anything.

Can you create separate issues for each item? This way it'll be easier to track & close individual issues.

> 3. I noticed in some of your functions code on the server, you're missing a few `return` statements in various spots. (An example of what i'm talking about is this) https://github.com/mavropalias/Hero35/blob/8122c134ca9a1cbc87c4bc4643fa894cdc806730/src/functions/index.ts#L212
>     There's various other spots that also have missing `return` statements in front of the `response.send` functions :)
>    **Edit**: Fixed all the missing return statements with this PR: #4

I was actually investigating this recently, due to an issue with some functions. Turns out you don't have to `return` on HTTP functions, like the one you linked above. They're properly terminated by `res.redirect()`, `res.send()`, or `res.end()`—[related docs](https://firebase.google.com/docs/functions/terminate-functions). 

> 4. I also don't see any functions to add/delete talks from the database. **How are new talks added to the database?**

There is a separate, private, repo with the admin panel of Hero35. It's built on React/MobX and connects directly to the database.

Talks are not added individually, but as part of an event (e.g. 'React Conf 2019').

The process of adding talks is:
1. Select an existing event, or create a new one.
![Screenshot 2020-02-03 at 09 56 09](https://user-images.githubusercontent.com/862852/73646073-8d5a2c80-4670-11ea-8e70-633e7f04fd13.png)
![Screenshot 2020-02-03 at 09 56 13](https://user-images.githubusercontent.com/862852/73646081-90551d00-4670-11ea-89ed-088606681043.png)
![Screenshot 2020-02-03 at 10 16 03](https://user-images.githubusercontent.com/862852/73646094-98ad5800-4670-11ea-941b-f47c9951e7f5.png)
2. Select an existing 'Edition' for that event, or create a new one.
![Screenshot 2020-02-03 at 09 56 42](https://user-images.githubusercontent.com/862852/73646196-cf836e00-4670-11ea-8ea8-164dc5434532.png)
![Screenshot 2020-02-03 at 10 26 36](https://user-images.githubusercontent.com/862852/73646203-d6aa7c00-4670-11ea-89a1-458dc29f61f9.png)
3. The app will search YouTube and find the edition playlist automatically. It will then parse all YouTube videos and convert them to talks, pre-populating many of the fields to make adding talks as quick as possible.
![Screenshot 2020-02-03 at 10 18 53](https://user-images.githubusercontent.com/862852/73646284-078ab100-4671-11ea-9c4d-ea0f48b400e5.png)
![Screenshot 2020-02-03 at 10 19 06](https://user-images.githubusercontent.com/862852/73646293-0ce7fb80-4671-11ea-9762-94dc8a36d553.png)
![Screenshot 2020-02-03 at 09 59 04](https://user-images.githubusercontent.com/862852/73646310-14a7a000-4671-11ea-8cff-f1bb83b8b9f2.png)

> 5. I see there's a `/country/[countryid]` route included in the project.. however don't see any pages that link to that page. Is this a page that was just never used or maybe is upcoming?

It is a page that was taken out of circulation, with the latest UI revamp of the home page. It's still there, though. Here are all [USA conferences](https://hero35.com/country/USA). I will add the option to view conferences by country, soon, with a planned UI revamp of the [Conferences](https://hero35.com/year/2020) page.

> I will keep updating this thread if you'd like to keep it open, and I can help spot errors as you add new updates, etc! @mavropalias

That's amazing, thank you so much. Feel free to open new tickets for specific issues.

**Comment by mavropalias** [comment]
> Stumbled upon a few more things that i'm a little concerned about with the cloud functions..
> 
> 1. For your `likeTalk` and `dislikeTalk` functions; you're storing the `dislikedUids` inside an array on the talk document.
>    https://github.com/mavropalias/Hero35/blob/8122c134ca9a1cbc87c4bc4643fa894cdc806730/src/functions/index.ts#L656
>    
>    From all the documentation on Firebase i've read, they have said that storing anything that has the ability to grow to an undetermined size should not be stored inside arrays, but rather inside a collection inside the document (using collection groups). Wouldn't it be better to store `Likes` and `Dislikes` inside a collection within the talk document they belong to? That way you could do something like `query(talkDocument)->query(likesSubCollection)->query(where(userId==x))` and same for dislikes.
> 
> **Note**: It look's like you're doing the same thing with a user saving talks. I think the best approach would be to similarly add the saves to a collection under the talk document it belongs to?
> 
> 1. Is there any reason why you're re-saving the talk data into an array on the user document. I understand why you want to duplicate this data into the user document (faster reads), however since this array could get infinitely sized, wouldn't be not a good idea to store this data like this?
>    https://github.com/mavropalias/Hero35/blob/8122c134ca9a1cbc87c4bc4643fa894cdc806730/src/functions/index.ts#L744-L758
> 
> Curious about your thoughts on what I mentioned, and please let me know if you disagree! I'm new to Firestore, so I could be completely wrong :)

It all depends on the data and how you want to access it.

Yes, theoretically, a user might go and like or save every single talk on Hero35. This might create issues in a few places, where we'll have to render a lot of stuff. 

In reality, users save up to a few tens of talks, where most only save less than 10. Similarly with likes, the amount of likes per user is far from becoming an issue. This will probably change _slowly_ as people use the site over time. But, even with hundreds of liked/saved talks, performance is fine.

So, not having to split the `talk` and `user` documents in sub-collections, has the following benefits:
1. allows me to write less code (and focus on other areas that need more attention)
2. makes all queries faster, since I only need to query a single document
3. the whole like/save process is simpler, hence less error-prone
4. querying for a user or talk, returns all needed data in one go, as needed by the UI

Keep in mind that Talks _are_ sub-collections of Editions, which are sub-collections of Events. They are architected that way, because this is how data needs to be queried. Plus, each collection group level contains redundant info about its parent (e.g. a Talk contain the Edition and Event IDs and names, so that it can be easily displayed on the [talk page](https://hero35.com/dotjs/2019/deno), without making additional queries), and in some cases of its children (an Edition contains an array of its Talks, so that it can display all talks on the [edition page](https://hero35.com/dotjs/2019), without additional queries). Similarly, User docs contain the saved talks data, so that they can be easily displayed on the [My Saved Talks](https://hero35.com/saved-talks) page.

**Comment by somepeopledontknow** [comment]
Thanks so much @mavropalias for your responses! I will keep pointing out any issues I see on the site! Can't wait to see other additions to the site. I think maybe an uplift to the profile page would be awesome; I think that's the only page I saw that was lacking a bit :)

**Comment by somepeopledontknow** [comment]
Closing this issue, as I will create seperate issue threads for upcoming issues.
